height = input("enter your height in m (use dot for decimal, for example 1.88): ")
weight = input("enter your weight in kg: ")
BMI = int(weight) / (float(height)**2)
BMI_as_int = int(BMI)
print("Your BMI is: ", BMI_as_int)